-- MySQL Script generated by MySQL Workbench
-- 12/06/15 22:38:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`summary_mstr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`summary_mstr` (
  `invoice_num` VARCHAR(10) NOT NULL COMMENT '',
  `invoice_total` VARCHAR(45) NOT NULL COMMENT '',
  `total_tax` VARCHAR(45) NOT NULL COMMENT '',
  `discount_pct` DECIMAL(3,2) NULL COMMENT '',
  `discount_amount` DECIMAL(10,2) NULL COMMENT '',
  `payment_duedate` DATE NULL COMMENT '',
  `tax_pct` DECIMAL(3,2) NULL COMMENT '',
  PRIMARY KEY (`invoice_num`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = dec8
COLLATE = dec8_bin;


-- -----------------------------------------------------
-- Table `mydb`.`item_mstr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_mstr` (
  `code` VARCHAR(10) NOT NULL COMMENT '',
  `uom` VARCHAR(3) NULL COMMENT '',
  `price_per_qty` DECIMAL(10,2) NULL COMMENT '',
  PRIMARY KEY (`code`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unitofmeasurement_mstr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unitofmeasurement_mstr` (
  `uom_code` VARCHAR(3) NOT NULL COMMENT '',
  `uom_description` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`uom_code`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoice_det`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoice_det` (
  `number` VARCHAR(10) NOT NULL COMMENT '',
  `line_number` VARCHAR(10) NOT NULL COMMENT '',
  `itemnumber` VARCHAR(10) NOT NULL COMMENT '',
  `uom` VARCHAR(10) NOT NULL COMMENT '',
  `quantity` INT NOT NULL COMMENT '',
  `lineprice` DECIMAL(10,2) NOT NULL COMMENT '',
  `item_mstr_code` VARCHAR(10) NOT NULL COMMENT '',
  `unitofmeasurement_mstr_uom_code` VARCHAR(3) NOT NULL COMMENT '',
  PRIMARY KEY (`number`, `line_number`)  COMMENT '',
  CONSTRAINT `fk_invoice_det_item_mstr1`
    FOREIGN KEY (`item_mstr_code`)
    REFERENCES `mydb`.`item_mstr` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_det_unitofmeasurement_mstr1`
    FOREIGN KEY (`unitofmeasurement_mstr_uom_code`)
    REFERENCES `mydb`.`unitofmeasurement_mstr` (`uom_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_invoice_det_item_mstr1_idx` ON `mydb`.`invoice_det` (`item_mstr_code` ASC)  COMMENT '';

CREATE INDEX `fk_invoice_det_unitofmeasurement_mstr1_idx` ON `mydb`.`invoice_det` (`unitofmeasurement_mstr_uom_code` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`address_mstr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address_mstr` (
  `type` VARCHAR(10) NOT NULL COMMENT '',
  `code` VARCHAR(10) NOT NULL COMMENT '',
  `line1` VARCHAR(45) NOT NULL COMMENT '',
  `line2` VARCHAR(45) NULL COMMENT '',
  `zip` VARCHAR(5) NOT NULL COMMENT '',
  `phone` VARCHAR(10) NULL COMMENT '',
  `email` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`code`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoice_header`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoice_header` (
  `number` VARCHAR(10) NOT NULL COMMENT '',
  `supplier` VARCHAR(10) NOT NULL COMMENT '',
  `billtocode` VARCHAR(10) NOT NULL COMMENT '',
  `purchaseordernumber` VARCHAR(10) NOT NULL COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  `remarks` VARCHAR(10) NULL COMMENT '',
  `summary_mstr_invoice_num` VARCHAR(10) NOT NULL COMMENT '',
  `invoice_det_number` VARCHAR(10) NOT NULL COMMENT '',
  `invoice_det_line_number` VARCHAR(10) NOT NULL COMMENT '',
  `address_mstr_code` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`number`, `supplier`)  COMMENT '',
  CONSTRAINT `fk_invoice_header_summary_mstr1`
    FOREIGN KEY (`summary_mstr_invoice_num`)
    REFERENCES `mydb`.`summary_mstr` (`invoice_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_header_invoice_det1`
    FOREIGN KEY (`invoice_det_number` , `invoice_det_line_number`)
    REFERENCES `mydb`.`invoice_det` (`number` , `line_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_header_address_mstr1`
    FOREIGN KEY (`address_mstr_code`)
    REFERENCES `mydb`.`address_mstr` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_invoice_header_summary_mstr1_idx` ON `mydb`.`invoice_header` (`summary_mstr_invoice_num` ASC)  COMMENT '';

CREATE INDEX `fk_invoice_header_invoice_det1_idx` ON `mydb`.`invoice_header` (`invoice_det_number` ASC, `invoice_det_line_number` ASC)  COMMENT '';

CREATE INDEX `fk_invoice_header_address_mstr1_idx` ON `mydb`.`invoice_header` (`address_mstr_code` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`header_mstr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`header_mstr` (
  `transmission_date` DATE NOT NULL COMMENT '',
  `invoice_num` VARCHAR(10) NOT NULL COMMENT '',
  `control_num` VARCHAR(10) NOT NULL COMMENT '',
  `sender_code` VARCHAR(10) NOT NULL COMMENT '',
  `receiver_code` VARCHAR(10) NOT NULL COMMENT '',
  `invoice_header_number` VARCHAR(10) NOT NULL COMMENT '',
  `invoice_header_supplier` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`invoice_num`, `receiver_code`, `sender_code`)  COMMENT '',
  CONSTRAINT `fk_header_mstr_invoice_header1`
    FOREIGN KEY (`invoice_header_number` , `invoice_header_supplier`)
    REFERENCES `mydb`.`invoice_header` (`number` , `supplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_header_mstr_invoice_header1_idx` ON `mydb`.`header_mstr` (`invoice_header_number` ASC, `invoice_header_supplier` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`supplier_mstr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier_mstr` (
  `soldto` VARCHAR(10) NOT NULL COMMENT '',
  `shipto` VARCHAR(10) NOT NULL COMMENT '',
  `taxable` TINYINT(1) NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `salesperson` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`soldto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplier_invoice_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier_invoice_history` (
  `invoice_number` VARCHAR(10) NOT NULL COMMENT '',
  `name` VARCHAR(10) NOT NULL COMMENT '',
  `invoice_header_number` VARCHAR(10) NOT NULL COMMENT '',
  `invoice_header_supplier` VARCHAR(10) NOT NULL COMMENT '',
  `supplier_mstr_soldto` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`invoice_number`, `name`)  COMMENT '',
  CONSTRAINT `fk_supplier_invoice_history_invoice_header1`
    FOREIGN KEY (`invoice_header_number` , `invoice_header_supplier`)
    REFERENCES `mydb`.`invoice_header` (`number` , `supplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplier_invoice_history_supplier_mstr1`
    FOREIGN KEY (`supplier_mstr_soldto`)
    REFERENCES `mydb`.`supplier_mstr` (`soldto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_supplier_invoice_history_invoice_header1_idx` ON `mydb`.`supplier_invoice_history` (`invoice_header_number` ASC, `invoice_header_supplier` ASC)  COMMENT '';

CREATE INDEX `fk_supplier_invoice_history_supplier_mstr1_idx` ON `mydb`.`supplier_invoice_history` (`supplier_mstr_soldto` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`zipcode_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zipcode_info` (
  `code` INT(5) NOT NULL COMMENT '',
  `city` VARCHAR(45) NULL COMMENT '',
  `state` VARCHAR(45) NULL COMMENT '',
  `country` VARCHAR(45) NULL COMMENT '',
  `address_mstr_code` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`code`)  COMMENT '',
  CONSTRAINT `fk_zipcode_info_address_mstr1`
    FOREIGN KEY (`address_mstr_code`)
    REFERENCES `mydb`.`address_mstr` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_zipcode_info_address_mstr1_idx` ON `mydb`.`zipcode_info` (`address_mstr_code` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `mydb`.`document_mstr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`document_mstr` (
  `doc_id` INT NOT NULL COMMENT '',
  `doc_name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`doc_id`, `doc_name`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table_mstr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table_mstr` (
  `tbl_id` INT NOT NULL COMMENT '',
  `tbl_name` VARCHAR(45) NOT NULL COMMENT '',
  `table_mstrcol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`tbl_id`, `tbl_name`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`column_mstr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`column_mstr` (
  `col_id` INT NOT NULL COMMENT '',
  `col_name` VARCHAR(45) NOT NULL COMMENT '',
  `col_tab_id` INT NOT NULL COMMENT '',
  `table_mstr_tbl_id` INT NOT NULL COMMENT '',
  `table_mstr_tbl_name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`col_id`, `col_name`, `col_tab_id`)  COMMENT '',
  CONSTRAINT `fk_column_mstr_table_mstr1`
    FOREIGN KEY (`table_mstr_tbl_id` , `table_mstr_tbl_name`)
    REFERENCES `mydb`.`table_mstr` (`tbl_id` , `tbl_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_column_mstr_table_mstr1_idx` ON `mydb`.`column_mstr` (`table_mstr_tbl_id` ASC, `table_mstr_tbl_name` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
